### ISSUE TITLE
Exceptions (Friends/Clan)

### ISSUE THREAD

**Issue by Anfoone** [TheStonedTurtle/unbalanced-trade-prevention#1]
Is it possible to add a opt-in (default off) toggle where if they are on my friends list or clan, that the plugin will not block trades? Friends and I trade gear between each other all the time for loans, would be a bit annoying to have to turn this off every time

**Comment by TheStonedTurtle** [comment]
You do not have to turn this plugin off, you can right-click the accept button to accept the trade.

But also, making the plugin not work for friends just seems like another avenue of abuse. Scammers will get you to add them before trying their scam, and most people would probably think "I can trust my friends, why not turn this on" and then forget about it when it comes to the above scenario.

**Comment by Anfoone** [comment]
Ah I did not know you could right-click accept still. Thanks for that!

Also you make a good point, it would not be uncommon for a scam to involve having to add each other to PM or anything, makes sense to me. Thanks again!

**Comment by TheStonedTurtle** [comment]
This feature was added in 66b85c7723c43a9483539c67582d0574b6cc52c2

Please refer to the README file for more information about how this feature works. The notably difference is that you must opt-in to the whitelisting for each friend, which should hopefully make this less likely to cause problems. Use at your own risk.
